# Generated by Django 2.2 on 2020-06-14 15:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EConsumptionDayAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('day_total', models.DecimalField(decimal_places=1, max_digits=17)),
                ('day_average', models.DecimalField(decimal_places=10, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000000)])),
                ('area', models.CharField(max_length=4)),
                ('tariff', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='UserEConsumptionDayAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('day_total', models.DecimalField(decimal_places=1, max_digits=7)),
                ('day_average', models.DecimalField(decimal_places=10, max_digits=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.User')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('consumption', models.DecimalField(decimal_places=1, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.User')),
            ],
        ),
    ]
